apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Values.name | toString  }}"
spec:
  endpoints:
  - path: /
    port: app
  namespaceSelector:
    matchNames:
    - argocd
  selector:
    matchLabels:
    {{- include "sysadvent2021.labels" . | nindent 6 }}
{{- if .Values.labels -}}
    {{- range $key, $value := .Values.labels }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}